---
title: "In-house statistics for the Vancouver Nighthawks of Major League Ultimate"
author: "Jenny Bryan"
date: "24 June, 2014"
output:
  html_document:
    theme: readable
    toc: true
---

Look under the hood: <https://github.com/jennybc/vanNH>

Now playing: <http://www.stat.ubc.ca/~jenny/notOcto/vanNH/vanNH_nowPlaying.html>

*Very beta* [Analysis of game play](analysis.html)

[Figures for a play-off preview article](2014-06-25_playoff-preview.html)

```{r include = FALSE, message = FALSE}
library(yaml)
library(plyr)
library(magrittr)
library(knitr)
library(xtable)

## I think I prefer an explicit whitelist approach here
# game_dir <- file.path("..", "games")
# list.files(game_dir)

## games for which I have data
tmp <- c("week game",
         "01   2014-04-12_vanNH-at-pdxST",
         "02   2014-04-20_sfoDF-at-vanNH",
         "03   2014-04-26_vanNH-at-seaRM",
         # 04 was a bye week for vanNH
         "05   2014-05-10_seaRM-at-vanNH",
         "06   2014-05-17_vanNH-at-sfoDF",
         "07   2014-05-24_pdxST-at-vanNH",
         "08   2014-05-31_vanNH-at-seaRM",
         "09   2014-06-07_seaRM-at-vanNH",
         "10   2014-06-15_pdxST-at-vanNH",
         "11   2014-06-21_vanNH-at-sfoDF",
         "01   2014-04-12_seaRM-at-sfoDF",
         "02   2014-04-19_sfoDF-at-seaRM",
         "03   2014-04-26_pdxST-at-sfoDF")
tmp <- read.table(text = tmp, header = TRUE,
                  colClasses = list(week = "character", game = "character"))

game_dirs <- file.path("..", "games", tmp$game)
yaml_files <-
  list.files(game_dirs, pattern = "at-last-point.yaml$", full.names = TRUE)
names(yaml_files) <- basename(dirname(yaml_files))
game_data <- ldply(yaml_files, function(x) {
  x %>% yaml.load_file %>% data.frame(stringsAsFactors = FALSE)})
game_data <- rename(game_data, c(".id" = "game"))
game_data <-
  subset(game_data,
         select = -c(point, period, clk_before, clk_after,
                     pull_team, scor_team))

## learn the date, home team, away team from the game ID
x <- unique(game_data$game)
m <- regexec("([-0-9]+)_([a-zA-Z]+)-at-([a-zA-Z]+)", x)
parsed_game_id <- ldply(regmatches(x, m), `[`, c(1L, 2L, 3L, 4L))
colnames(parsed_game_id) <- c("game", "date","awayTeam","homeTeam")
game_data <- join(game_data, parsed_game_id)
game_data <- join(game_data, tmp)

## sub-data.frame for games involving vanNH
## add many more derived variables
vanNH_data <- subset(game_data, !is.na(vanNH))
vanNH_data <-
  mutate(vanNH_data,
         status = ifelse(homeTeam == "vanNH", "home", "away"))
all_teams <- with(vanNH_data, sort(unique(c(awayTeam, homeTeam))))
opponents <- all_teams[all_teams != "vanNH"]
vanNH_data$opponent <- 
  aaply(vanNH_data[opponents], 1,
        function(x) opponents[!is.na(x)], .expand = FALSE)
vanNH_data$oppScore <- 
  aaply(vanNH_data[opponents], 1, function(x) x[!is.na(x)], .expand = FALSE)
vanNH_data <- transform(vanNH_data,
                        outcome = ifelse(vanNH > oppScore, "W", "L"),
                        pt_diff = vanNH - oppScore,
                        final = I(paste0("vanNH: ", vanNH, "  ",
                                         opponent, ": ", oppScore)),
                        us = I(paste0("vanNH: ", vanNH)),
                        them = I(paste0(opponent, ": ", oppScore)),
                        # link = I(paste0('<a href=http://www.stat.ubc.ca/~jenny/',
                        # 'notOcto/vanNH/', game_data$game,
                        # '_live-stats.html>', date, '</a>')))
                        link = I(paste0('<a href=', game,
                                        '_live-stats.html>', date, '</a>')))

pretty_vars <- c("week", "link", "status", "us", "them", "outcome",
                 "pt_diff")
pretty_stuff <- vanNH_data[pretty_vars]
pretty_stuff <- rename(pretty_stuff, c("link" = "date"))

## convert to character, then add a last row with relevant summaries
pretty_stuff <- as.matrix(colwise(as.character)(pretty_stuff))
n <- nrow(pretty_stuff)
pretty_stuff <- pretty_stuff[c(seq_len(n), n), ]
pretty_stuff[n + 1, ] <- ""
pretty_stuff[n + 1, "us"] <- paste0("vanNH: ", sum(vanNH_data$vanNH))
pretty_stuff[n + 1, "them"] <- paste0("opp: ", sum(vanNH_data$oppScore))
pretty_stuff[n + 1, "pt_diff"] <- as.character(sum(vanNH_data$pt_diff))
pretty_stuff[n + 1, "outcome"] <- 
  with(vanNH_data, paste0(sum(outcome == "W"),
                          "W - ", sum(outcome == "L"), "L"))

## sub-data.frame for games NOT involving vanNH
## add many more derived variables
othwc_data <- subset(game_data, is.na(vanNH))
othwc_data <- transform(othwc_data,
                        link = I(paste0('<a href=', game,
                                        '_live-stats.html>', date, '</a>')))

othwc_pretty_vars <- c("week", "link", "pdxST", "seaRM", "sfoDF")
othwc_pretty_stuff <- othwc_data[othwc_pretty_vars]
othwc_pretty_stuff <- rename(othwc_pretty_stuff, c("link" = "date"))

## convert to character, then add a last row with relevant summaries
othwc_pretty_stuff <- as.matrix(colwise(as.character)(othwc_pretty_stuff))
jFun <- function(x) {x[is.na(x)] <- ""; return(x)}
othwc_pretty_stuff[ , c('pdxST', 'seaRM', 'sfoDF')] <- 
  apply(othwc_pretty_stuff[ , c('pdxST', 'seaRM', 'sfoDF')], 2, jFun)
```

## Games involving the Vancouver Nighthawks.

Click on a date to see stats for a game.

```{r echo = FALSE, results = 'asis'}
kable(pretty_stuff)
```

Week 04 was a bye week for vanNH.  

## Other games in the MLU Western Conference.

Click on a date to see stats for a game.

```{r echo = FALSE, results = 'asis'}
kable(othwc_pretty_stuff)
```

```{r results = 'asis', echo = FALSE, eval = FALSE}
print(xtable(pretty_stuff, type = "html", sanitize.text.function = force),
      type = "html", comment = FALSE)
```

